name: Release

on:
  push:
    branches: [ "release" ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout mdblog
        run: git clone https://github.com/toonvd/mdblog.git
        working-directory: ../mdblog
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
        working-directory: ../mdblog
      - name: Composer install
        run: composer install --prefer-dist --no-progress
        working-directory: ../mdblog
      - name: Build blog pages
        run: >
          php application generate:blog 
          --source=${GITHUB_WORKSPACE}/.blogposts/
          --target=${GITHUB_WORKSPACE}/
          --base_url=https://toonvd.github.io
          --image_path=${GITHUB_WORKSPACE}/images/
          --template_path=${GITHUB_WORKSPACE}/.templates/
        working-directory: ../mdblog
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: New release
      - name: Merge to main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: release
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}